### ISSUE TITLE
search.json loaded, but not found

### ISSUE THREAD

**Issue by 3noki** [christian-fei/Simple-Jekyll-Search#118]
Serving locally the script cannot find the search.json file even though it's loaded (will be serving from github later)

![image](https://user-images.githubusercontent.com/26792640/54089709-79f3f380-4331-11e9-9827-f09cd5fe0e49.png)

The script is loaded fine, I added another script to try and load the json data before the assets/js/script.js is run, but have not been successful so far;

```
    <script>
    fetch('./search.json').then(response => {
      return response.json();
    }).then(data => {
      console.log(data);
    }).catch(err => {
    });
    </script>
```

Any of the following urls have not been working;

![image](https://user-images.githubusercontent.com/26792640/54089762-21712600-4332-11e9-9f60-aaf8ad28d6c0.png)

I am thinking this has to do with the fact that the jekyll search script is getting loaded before the search.json file is, resulting in the error that it can't find it, would make sense to me, or there is a problem with the url, what other options would there be for a base url?

**Comment by johnnymythology** [comment]
I managed to fix this issue by looking at other people's code, specifically (https://github.com/lynn9388/light-blog/blob/f43172f7aae9f18c09c9c1a24f948e7929bff522/_includes/modules/search-box.html)

It turns out, you need to add {{ site.url }} in the js script and add baseurl in the _config.yml file. 
`var sjs = SimpleJekyllSearch({
    searchInput: document.getElementById('search-input'),
    resultsContainer: document.getElementById('results-container'),
    json: '{{ site.base_url }}/search.json'
    })`

`port: 4000
host: 127.0.0.1
baseurl: ""
url: /`

Until now, I have only tested it locally. I will update once I publish my blog on Github Pages.

Hope this helps!

**Comment by christian-fei** [comment]
This is a configuration issue with you `search.json` 

please refer to https://jekyllrb.com/docs/liquid/
